# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: kibana-no-security
  labels:
    app: kibana
data:
  kibana.yml: |-
    ---
    # Default Kibana configuration from kibana-docker.
    server.name: kibana
    server.host: "0.0.0.0"

    # Replace with Elasticsearch DNS name picked during Service deployment
    elasticsearch.hosts: ["${ELASTICSEARCH_URL}"]
    elasticsearch.requestTimeout: 360000
