apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opendistro-elasticsearch-bbl-pvc
  namespace: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
